version: "3.8"

services:
  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    restart: always
    command:
      - "--api.insecure=false"  # Enable Traefik dashboard (for testing)
      - "--providers.docker=true"  # Enable automatic service discovery
      - "--entrypoints.web.address=:80"  # HTTP port
      - "--entrypoints.websecure.address=:443"  # HTTPS port
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # Let's Encrypt Configuration
      - "--certificatesresolvers.myresolver.acme.email=user@peacewalker.my.id"  # Replace with your email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Allows Traefik to detect containers
      - "./letsencrypt:/letsencrypt"  # Persist Let's Encrypt certificates

  frontend:
    image: "ghcr.io/peacewalker122/e2e-chat:latest-fe"
    container_name: "chatapp-frontend"
    restart: always
    environment:
        VITE_ENV: production
        VITE_WS_URL: ws://api.peacewalker.my.id/ws
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`chat.peacewalker.my.id`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  backend:
    image: "ghcr.io/peacewalker122/e2e-chat:latest-be"
    container_name: "relay-server"
    restart: always
    labels:
      - "traefik.http.routers.websocket.rule=Host(`api.peacewalker.my.id`) && PathPrefix(`/ws`)"
      - "traefik.http.routers.websocket.entrypoints=websecure"
      - "traefik.http.routers.websocket.tls=true"
      - "traefik.http.routers.websocket.tls.certresolver=myresolver"
      - "traefik.http.services.websocket.loadbalancer.server.port=8000"
      # Add middleware to strip prefix
      - "traefik.http.middlewares.strip-ws-prefix.stripprefix.prefixes=/ws"
      - "traefik.http.routers.websocket.middlewares=strip-ws-prefix@docker"
