name: Deploy Full-Stack Vite + WebSocket App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build & Push Frontend Image
        run: |
          FRONTEND_IMAGE=ghcr.io/${{ secrets.GHCR_USERNAME }}/vite-frontend:latest
          docker build -t $FRONTEND_IMAGE -f Dockerfile.frontend .
          docker push $FRONTEND_IMAGE

      - name: Build & Push Backend Image
        run: |
          BACKEND_IMAGE=ghcr.io/${{ secrets.GHCR_USERNAME }}/ws-backend:latest
          docker build -t $BACKEND_IMAGE -f Dockerfile.backend .
          docker push $BACKEND_IMAGE

      - name: Upload Docker Compose to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/"

      - name: SSH into VPS & Deploy with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/vite-frontend:latest
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/ws-backend:latest
            docker-compose -f ~/docker-compose.yml up -d --force-recreate
